parameters:
#    braincrafted_bootstrap.example.class: Braincrafted\BootstrapBundle\Example

services:
    braincrafted.bootstrap.voter.request:
        class: Braincrafted\BootstrapBundle\Voter\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
#    braincrafted_bootstrap.example:
#        class: %braincrafted_bootstrap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
